// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: highlights.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const listHighlightBooksByUserID = `-- name: ListHighlightBooksByUserID :many
SELECT
    asin,
    COALESCE(MAX(book_title), '')::text AS book_title,
    COALESCE(MAX(book_author), '')::text AS book_author,
    COUNT(*) AS highlight_count,
    source
FROM highlights
WHERE user_id = $1
  AND asin IS NOT NULL
  AND source = $2
GROUP BY asin, source
ORDER BY MAX(highlighted_at) DESC NULLS LAST, MAX(created_at) DESC
`

type ListHighlightBooksByUserIDParams struct {
	UserID uuid.UUID      `json:"user_id"`
	Source sql.NullString `json:"source"`
}

type ListHighlightBooksByUserIDRow struct {
	Asin           sql.NullString `json:"asin"`
	BookTitle      string         `json:"book_title"`
	BookAuthor     string         `json:"book_author"`
	HighlightCount int64          `json:"highlight_count"`
	Source         sql.NullString `json:"source"`
}

func (q *Queries) ListHighlightBooksByUserID(ctx context.Context, arg ListHighlightBooksByUserIDParams) ([]ListHighlightBooksByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listHighlightBooksByUserID, arg.UserID, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHighlightBooksByUserIDRow{}
	for rows.Next() {
		var i ListHighlightBooksByUserIDRow
		if err := rows.Scan(
			&i.Asin,
			&i.BookTitle,
			&i.BookAuthor,
			&i.HighlightCount,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHighlightExplanation = `-- name: UpdateHighlightExplanation :one
UPDATE highlights
SET explanation = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, book_id, content, location, created_at, book_title, book_author, asin, highlighted_at, source, updated_at, content_hash, explanation, source_app, source_url, status, retry_count, generation_requested_at, processing_started_at, completed_at, failed_at, last_error, book_key, book_order_index
`

type UpdateHighlightExplanationParams struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	Explanation sql.NullString `json:"explanation"`
}

func (q *Queries) UpdateHighlightExplanation(ctx context.Context, arg UpdateHighlightExplanationParams) (Highlight, error) {
	row := q.db.QueryRowContext(ctx, updateHighlightExplanation, arg.ID, arg.UserID, arg.Explanation)
	var i Highlight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Content,
		&i.Location,
		&i.CreatedAt,
		&i.BookTitle,
		&i.BookAuthor,
		&i.Asin,
		&i.HighlightedAt,
		&i.Source,
		&i.UpdatedAt,
		&i.ContentHash,
		&i.Explanation,
		&i.SourceApp,
		&i.SourceUrl,
		&i.Status,
		&i.RetryCount,
		&i.GenerationRequestedAt,
		&i.ProcessingStartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.LastError,
		&i.BookKey,
		&i.BookOrderIndex,
	)
	return i, err
}
