// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: highlights.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const listHighlightBooksByUserID = `-- name: ListHighlightBooksByUserID :many
SELECT
    asin,
    COALESCE(MAX(book_title), '')::text AS book_title,
    COALESCE(MAX(book_author), '')::text AS book_author,
    COUNT(*) AS highlight_count,
    source
FROM highlights
WHERE user_id = $1
  AND asin IS NOT NULL
  AND source = $2
GROUP BY asin, source
ORDER BY MAX(highlighted_at) DESC NULLS LAST, MAX(created_at) DESC
`

type ListHighlightBooksByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Source string    `json:"source"`
}

type ListHighlightBooksByUserIDRow struct {
	Asin           sql.NullString `json:"asin"`
	BookTitle      string         `json:"book_title"`
	BookAuthor     string         `json:"book_author"`
	HighlightCount int64          `json:"highlight_count"`
	Source         string         `json:"source"`
}

func (q *Queries) ListHighlightBooksByUserID(ctx context.Context, arg ListHighlightBooksByUserIDParams) ([]ListHighlightBooksByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listHighlightBooksByUserID, arg.UserID, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHighlightBooksByUserIDRow{}
	for rows.Next() {
		var i ListHighlightBooksByUserIDRow
		if err := rows.Scan(
			&i.Asin,
			&i.BookTitle,
			&i.BookAuthor,
			&i.HighlightCount,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHighlightsByUserIDAndASIN = `-- name: ListHighlightsByUserIDAndASIN :many
SELECT
    id, user_id, book_id, content, location, created_at,
    book_title, book_author, asin, highlighted_at, source, updated_at,
    content_hash, explanation, source_app, source_url, status, retry_count,
    generation_requested_at, processing_started_at, completed_at, failed_at, last_error
FROM highlights
WHERE user_id = $1
  AND asin = $2
  AND source = $3
ORDER BY highlighted_at ASC NULLS LAST, created_at ASC
`

type ListHighlightsByUserIDAndASINParams struct {
	UserID uuid.UUID      `json:"user_id"`
	Asin   sql.NullString `json:"asin"`
	Source string         `json:"source"`
}

func (q *Queries) ListHighlightsByUserIDAndASIN(ctx context.Context, arg ListHighlightsByUserIDAndASINParams) ([]Highlight, error) {
	rows, err := q.db.QueryContext(ctx, listHighlightsByUserIDAndASIN, arg.UserID, arg.Asin, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Highlight{}
	for rows.Next() {
		var i Highlight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Content,
			&i.Location,
			&i.CreatedAt,
			&i.BookTitle,
			&i.BookAuthor,
			&i.Asin,
			&i.HighlightedAt,
			&i.Source,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.Explanation,
			&i.SourceApp,
			&i.SourceUrl,
			&i.Status,
			&i.RetryCount,
			&i.GenerationRequestedAt,
			&i.ProcessingStartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHighlightsByUserIDAndBookMetadata = `-- name: ListHighlightsByUserIDAndBookMetadata :many
SELECT
    id, user_id, book_id, content, location, created_at,
    book_title, book_author, asin, highlighted_at, source, updated_at,
    content_hash, explanation, source_app, source_url, status, retry_count,
    generation_requested_at, processing_started_at, completed_at, failed_at, last_error
FROM highlights
WHERE user_id = $1
  AND source = $2
  AND lower(trim(coalesce(book_title, ''))) = lower(trim($3))
  AND lower(trim(coalesce(book_author, ''))) = lower(trim($4))
ORDER BY highlighted_at ASC NULLS LAST, created_at ASC
`

type ListHighlightsByUserIDAndBookMetadataParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Source     string    `json:"source"`
	BookTitle  string    `json:"book_title"`
	BookAuthor string    `json:"book_author"`
}

func (q *Queries) ListHighlightsByUserIDAndBookMetadata(ctx context.Context, arg ListHighlightsByUserIDAndBookMetadataParams) ([]Highlight, error) {
	rows, err := q.db.QueryContext(ctx, listHighlightsByUserIDAndBookMetadata,
		arg.UserID,
		arg.Source,
		arg.BookTitle,
		arg.BookAuthor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Highlight{}
	for rows.Next() {
		var i Highlight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Content,
			&i.Location,
			&i.CreatedAt,
			&i.BookTitle,
			&i.BookAuthor,
			&i.Asin,
			&i.HighlightedAt,
			&i.Source,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.Explanation,
			&i.SourceApp,
			&i.SourceUrl,
			&i.Status,
			&i.RetryCount,
			&i.GenerationRequestedAt,
			&i.ProcessingStartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHighlightsByUserIDAndBookTitle = `-- name: ListHighlightsByUserIDAndBookTitle :many
SELECT
    id, user_id, book_id, content, location, created_at,
    book_title, book_author, asin, highlighted_at, source, updated_at,
    content_hash, explanation, source_app, source_url, status, retry_count,
    generation_requested_at, processing_started_at, completed_at, failed_at, last_error
FROM highlights
WHERE user_id = $1
  AND source = $2
  AND lower(trim(coalesce(book_title, ''))) = lower(trim($3))
ORDER BY highlighted_at ASC NULLS LAST, created_at ASC
`

type ListHighlightsByUserIDAndBookTitleParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Source    string    `json:"source"`
	BookTitle string    `json:"book_title"`
}

func (q *Queries) ListHighlightsByUserIDAndBookTitle(ctx context.Context, arg ListHighlightsByUserIDAndBookTitleParams) ([]Highlight, error) {
	rows, err := q.db.QueryContext(ctx, listHighlightsByUserIDAndBookTitle, arg.UserID, arg.Source, arg.BookTitle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Highlight{}
	for rows.Next() {
		var i Highlight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Content,
			&i.Location,
			&i.CreatedAt,
			&i.BookTitle,
			&i.BookAuthor,
			&i.Asin,
			&i.HighlightedAt,
			&i.Source,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.Explanation,
			&i.SourceApp,
			&i.SourceUrl,
			&i.Status,
			&i.RetryCount,
			&i.GenerationRequestedAt,
			&i.ProcessingStartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHighlightExplanation = `-- name: UpdateHighlightExplanation :one
UPDATE highlights
SET explanation = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING
    id, user_id, book_id, content, location, created_at,
    book_title, book_author, asin, highlighted_at, source, updated_at,
    content_hash, explanation, source_app, source_url, status, retry_count,
    generation_requested_at, processing_started_at, completed_at, failed_at, last_error
`

type UpdateHighlightExplanationParams struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	Explanation sql.NullString `json:"explanation"`
}

func (q *Queries) UpdateHighlightExplanation(ctx context.Context, arg UpdateHighlightExplanationParams) (Highlight, error) {
	row := q.db.QueryRowContext(ctx, updateHighlightExplanation, arg.ID, arg.UserID, arg.Explanation)
	var i Highlight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Content,
		&i.Location,
		&i.CreatedAt,
		&i.BookTitle,
		&i.BookAuthor,
		&i.Asin,
		&i.HighlightedAt,
		&i.Source,
		&i.UpdatedAt,
		&i.ContentHash,
		&i.Explanation,
		&i.SourceApp,
		&i.SourceUrl,
		&i.Status,
		&i.RetryCount,
		&i.GenerationRequestedAt,
		&i.ProcessingStartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.LastError,
	)
	return i, err
}
