// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Answer struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	QuestionID  uuid.UUID      `json:"question_id"`
	UserAnswer  string         `json:"user_answer"`
	IsCorrect   bool           `json:"is_correct"`
	CreatedAt   time.Time      `json:"created_at"`
	Score       sql.NullInt32  `json:"score"`
	Feedback    sql.NullString `json:"feedback"`
	GraderModel sql.NullString `json:"grader_model"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Book struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Author        sql.NullString `json:"author"`
	Isbn          sql.NullString `json:"isbn"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	FieldID       uuid.NullUUID  `json:"field_id"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Comment struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	PostID    uuid.UUID `json:"post_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	Content   string    `json:"content"`
}

type Field struct {
	ID        uuid.UUID     `json:"id"`
	Name      string        `json:"name"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	CreatedAt time.Time     `json:"created_at"`
}

type Follow struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Highlight struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	BookID        uuid.NullUUID  `json:"book_id"`
	Content       string         `json:"content"`
	Location      sql.NullString `json:"location"`
	CreatedAt     time.Time      `json:"created_at"`
	BookTitle     sql.NullString `json:"book_title"`
	BookAuthor    sql.NullString `json:"book_author"`
	Asin          sql.NullString `json:"asin"`
	HighlightedAt sql.NullTime   `json:"highlighted_at"`
	Source        string         `json:"source"`
	UpdatedAt     time.Time      `json:"updated_at"`
	ContentHash   sql.NullString `json:"content_hash"`
	Explanation   sql.NullString `json:"explanation"`
}

type Like struct {
	UserID    uuid.UUID `json:"user_id"`
	PostID    uuid.UUID `json:"post_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Post struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	QuestionID    uuid.NullUUID  `json:"question_id"`
	BookID        uuid.NullUUID  `json:"book_id"`
	FieldID       uuid.NullUUID  `json:"field_id"`
	Type          string         `json:"type"`
	RepostCount   int32          `json:"repost_count"`
	LikeCount     int32          `json:"like_count"`
	CommentCount  int32          `json:"comment_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	Body          sql.NullString `json:"body"`
	BookTitle     sql.NullString `json:"book_title"`
	QuestionCount int32          `json:"question_count"`
}

type PostQuestion struct {
	PostID     uuid.UUID      `json:"post_id"`
	QuestionID uuid.UUID      `json:"question_id"`
	SortOrder  int32          `json:"sort_order"`
	Note       sql.NullString `json:"note"`
}

type Question struct {
	ID                uuid.UUID             `json:"id"`
	UserID            uuid.UUID             `json:"user_id"`
	FieldID           uuid.NullUUID         `json:"field_id"`
	SourceType        string                `json:"source_type"`
	QuestionType      string                `json:"question_type"`
	Body              string                `json:"body"`
	Options           pqtype.NullRawMessage `json:"options"`
	CorrectAnswer     string                `json:"correct_answer"`
	Explanation       sql.NullString        `json:"explanation"`
	CustomInstruction sql.NullString        `json:"custom_instruction"`
	AnswerCount       int32                 `json:"answer_count"`
	CorrectCount      int32                 `json:"correct_count"`
	IsAiGenerated     bool                  `json:"is_ai_generated"`
	CreatedAt         time.Time             `json:"created_at"`
	UpdatedAt         time.Time             `json:"updated_at"`
	GenerationID      uuid.NullUUID         `json:"generation_id"`
	HighlightID       uuid.NullUUID         `json:"highlight_id"`
}

type QuestionGeneration struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	SourceType string         `json:"source_type"`
	SourceID   uuid.NullUUID  `json:"source_id"`
	PromptUsed sql.NullString `json:"prompt_used"`
	ModelUsed  sql.NullString `json:"model_used"`
	CreatedAt  time.Time      `json:"created_at"`
}

type Repost struct {
	UserID    uuid.UUID `json:"user_id"`
	PostID    uuid.UUID `json:"post_id"`
	CreatedAt time.Time `json:"created_at"`
}

type SavedQuestion struct {
	UserID     uuid.UUID      `json:"user_id"`
	QuestionID uuid.UUID      `json:"question_id"`
	CreatedAt  time.Time      `json:"created_at"`
	Note       sql.NullString `json:"note"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type User struct {
	ID                   uuid.UUID      `json:"id"`
	FirebaseUid          string         `json:"firebase_uid"`
	Username             string         `json:"username"`
	DisplayName          string         `json:"display_name"`
	AvatarUrl            sql.NullString `json:"avatar_url"`
	Bio                  sql.NullString `json:"bio"`
	University           sql.NullString `json:"university"`
	Faculty              sql.NullString `json:"faculty"`
	Grade                sql.NullInt16  `json:"grade"`
	Country              sql.NullString `json:"country"`
	Plan                 string         `json:"plan"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DefaultQuestionCount int16          `json:"default_question_count"`
}

type UserBook struct {
	UserID    uuid.UUID `json:"user_id"`
	BookID    uuid.UUID `json:"book_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserInterest struct {
	UserID    uuid.UUID `json:"user_id"`
	FieldID   uuid.UUID `json:"field_id"`
	CreatedAt time.Time `json:"created_at"`
}
