// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Answer struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	QuestionID uuid.UUID `json:"question_id"`
	UserAnswer string    `json:"user_answer"`
	IsCorrect  bool      `json:"is_correct"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Book struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Author        sql.NullString `json:"author"`
	Isbn          sql.NullString `json:"isbn"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	FieldID       uuid.NullUUID  `json:"field_id"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Comment struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	PostID    uuid.UUID `json:"post_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	Content   string    `json:"content"`
}

type Field struct {
	ID        uuid.UUID     `json:"id"`
	Name      string        `json:"name"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	CreatedAt time.Time     `json:"created_at"`
}

type Follow struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Highlight struct {
	ID                    uuid.UUID      `json:"id"`
	UserID                uuid.UUID      `json:"user_id"`
	BookID                uuid.NullUUID  `json:"book_id"`
	Content               string         `json:"content"`
	Location              sql.NullString `json:"location"`
	CreatedAt             time.Time      `json:"created_at"`
	BookTitle             sql.NullString `json:"book_title"`
	BookAuthor            sql.NullString `json:"book_author"`
	Asin                  sql.NullString `json:"asin"`
	HighlightedAt         sql.NullTime   `json:"highlighted_at"`
	Source                sql.NullString `json:"source"`
	UpdatedAt             time.Time      `json:"updated_at"`
	ContentHash           sql.NullString `json:"content_hash"`
	Explanation           sql.NullString `json:"explanation"`
	SourceApp             sql.NullString `json:"source_app"`
	SourceUrl             sql.NullString `json:"source_url"`
	Status                string         `json:"status"`
	RetryCount            int32          `json:"retry_count"`
	GenerationRequestedAt time.Time      `json:"generation_requested_at"`
	ProcessingStartedAt   sql.NullTime   `json:"processing_started_at"`
	CompletedAt           sql.NullTime   `json:"completed_at"`
	FailedAt              sql.NullTime   `json:"failed_at"`
	LastError             sql.NullString `json:"last_error"`
	BookKey               sql.NullString `json:"book_key"`
	BookOrderIndex        sql.NullInt32  `json:"book_order_index"`
}

type HighlightImportQueue struct {
	ID                  uuid.UUID       `json:"id"`
	UserID              uuid.UUID       `json:"user_id"`
	Source              string          `json:"source"`
	RawPayload          json.RawMessage `json:"raw_payload"`
	Status              string          `json:"status"`
	RetryCount          int32           `json:"retry_count"`
	LastError           sql.NullString  `json:"last_error"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	ProcessingStartedAt sql.NullTime    `json:"processing_started_at"`
	CompletedAt         sql.NullTime    `json:"completed_at"`
	FailedAt            sql.NullTime    `json:"failed_at"`
}

type Like struct {
	UserID    uuid.UUID `json:"user_id"`
	PostID    uuid.UUID `json:"post_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Post struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	QuestionID    uuid.NullUUID  `json:"question_id"`
	BookID        uuid.NullUUID  `json:"book_id"`
	FieldID       uuid.NullUUID  `json:"field_id"`
	Type          string         `json:"type"`
	RepostCount   int32          `json:"repost_count"`
	LikeCount     int32          `json:"like_count"`
	CommentCount  int32          `json:"comment_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	Body          sql.NullString `json:"body"`
	BookTitle     sql.NullString `json:"book_title"`
	QuestionCount int32          `json:"question_count"`
}

type PostQuestion struct {
	PostID     uuid.UUID      `json:"post_id"`
	QuestionID uuid.UUID      `json:"question_id"`
	SortOrder  int32          `json:"sort_order"`
	Note       sql.NullString `json:"note"`
}

type Question struct {
	ID                uuid.UUID             `json:"id"`
	UserID            uuid.UUID             `json:"user_id"`
	FieldID           uuid.NullUUID         `json:"field_id"`
	SourceType        string                `json:"source_type"`
	QuestionType      string                `json:"question_type"`
	Body              string                `json:"body"`
	Options           pqtype.NullRawMessage `json:"options"`
	CorrectAnswer     string                `json:"correct_answer"`
	Explanation       sql.NullString        `json:"explanation"`
	CustomInstruction sql.NullString        `json:"custom_instruction"`
	AnswerCount       int32                 `json:"answer_count"`
	CorrectCount      int32                 `json:"correct_count"`
	IsAiGenerated     bool                  `json:"is_ai_generated"`
	CreatedAt         time.Time             `json:"created_at"`
	UpdatedAt         time.Time             `json:"updated_at"`
	GenerationID      uuid.NullUUID         `json:"generation_id"`
	HighlightID       uuid.NullUUID         `json:"highlight_id"`
	Perspective       string                `json:"perspective"`
	Version           int32                 `json:"version"`
	SupersededAt      sql.NullTime          `json:"superseded_at"`
}

type QuestionDailyBudget struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	BudgetDate   time.Time `json:"budget_date"`
	FreeUsed     int32     `json:"free_used"`
	TokenUsed    int32     `json:"token_used"`
	AdViewsToday int32     `json:"ad_views_today"`
	CreatedAt    time.Time `json:"created_at"`
}

type QuestionGeneration struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	SourceType string         `json:"source_type"`
	SourceID   uuid.NullUUID  `json:"source_id"`
	PromptUsed sql.NullString `json:"prompt_used"`
	ModelUsed  sql.NullString `json:"model_used"`
	CreatedAt  time.Time      `json:"created_at"`
}

type QuestionGenerationJob struct {
	ID                  uuid.UUID      `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	BookKey             string         `json:"book_key"`
	Status              string         `json:"status"`
	Reason              string         `json:"reason"`
	RetryCount          int32          `json:"retry_count"`
	LastError           sql.NullString `json:"last_error"`
	CreatedAt           time.Time      `json:"created_at"`
	ProcessingStartedAt sql.NullTime   `json:"processing_started_at"`
	CompletedAt         sql.NullTime   `json:"completed_at"`
	FailedAt            sql.NullTime   `json:"failed_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type QuestionGenerationJobHighlight struct {
	JobID                uuid.UUID `json:"job_id"`
	HighlightID          uuid.UUID `json:"highlight_id"`
	PlannedQuestionCount int32     `json:"planned_question_count"`
}

type RateLimitCounter struct {
	UserID    string    `json:"user_id"`
	Bucket    string    `json:"bucket"`
	Period    time.Time `json:"period"`
	Count     int64     `json:"count"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RegenerationQueue struct {
	ID                      uuid.UUID      `json:"id"`
	UserID                  uuid.UUID      `json:"user_id"`
	HighlightID             uuid.UUID      `json:"highlight_id"`
	RequestedFromQuestionID uuid.NullUUID  `json:"requested_from_question_id"`
	Reason                  string         `json:"reason"`
	Status                  string         `json:"status"`
	RetryCount              int32          `json:"retry_count"`
	RequestedAt             time.Time      `json:"requested_at"`
	ProcessingStartedAt     sql.NullTime   `json:"processing_started_at"`
	CompletedAt             sql.NullTime   `json:"completed_at"`
	FailedAt                sql.NullTime   `json:"failed_at"`
	LastError               sql.NullString `json:"last_error"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}

type Repost struct {
	UserID    uuid.UUID `json:"user_id"`
	PostID    uuid.UUID `json:"post_id"`
	CreatedAt time.Time `json:"created_at"`
}

type SavedQuestion struct {
	UserID     uuid.UUID      `json:"user_id"`
	QuestionID uuid.UUID      `json:"question_id"`
	CreatedAt  time.Time      `json:"created_at"`
	Note       sql.NullString `json:"note"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type User struct {
	ID                    uuid.UUID      `json:"id"`
	FirebaseUid           string         `json:"firebase_uid"`
	Username              string         `json:"username"`
	DisplayName           string         `json:"display_name"`
	AvatarUrl             sql.NullString `json:"avatar_url"`
	Bio                   sql.NullString `json:"bio"`
	University            sql.NullString `json:"university"`
	Faculty               sql.NullString `json:"faculty"`
	Grade                 sql.NullInt16  `json:"grade"`
	Country               sql.NullString `json:"country"`
	Plan                  string         `json:"plan"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	DefaultQuestionCount  int16          `json:"default_question_count"`
	LastSyncAt            sql.NullTime   `json:"last_sync_at"`
	StripeCustomerID      sql.NullString `json:"stripe_customer_id"`
	StripeSubscriptionID  sql.NullString `json:"stripe_subscription_id"`
	SubscriptionExpiresAt sql.NullTime   `json:"subscription_expires_at"`
}

type UserAdToken struct {
	ID         uuid.UUID     `json:"id"`
	UserID     uuid.UUID     `json:"user_id"`
	TokenCount int32         `json:"token_count"`
	EarnedAt   time.Time     `json:"earned_at"`
	UsedAt     sql.NullTime  `json:"used_at"`
	JobID      uuid.NullUUID `json:"job_id"`
}

type UserBook struct {
	UserID    uuid.UUID `json:"user_id"`
	BookID    uuid.UUID `json:"book_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserDailyGenerationCount struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
	Count  int32     `json:"count"`
}

type UserInterest struct {
	UserID    uuid.UUID `json:"user_id"`
	FieldID   uuid.UUID `json:"field_id"`
	CreatedAt time.Time `json:"created_at"`
}
