// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    firebase_uid,
    email,
    username,
    display_name,
    avatar_url,
    bio,
    university,
    faculty,
    grade,
    country,
    plan
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'free'
)
RETURNING id, firebase_uid, username, display_name, avatar_url, bio, university, faculty, grade, country, plan, created_at, updated_at, default_question_count, last_sync_at, stripe_customer_id, stripe_subscription_id, subscription_expires_at
`

type CreateUserParams struct {
	FirebaseUid string         `json:"firebase_uid"`
	Email       sql.NullString `json:"email"`
	Username    string         `json:"username"`
	DisplayName string         `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Bio         sql.NullString `json:"bio"`
	University  sql.NullString `json:"university"`
	Faculty     sql.NullString `json:"faculty"`
	Grade       sql.NullInt16  `json:"grade"`
	Country     sql.NullString `json:"country"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirebaseUid,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Bio,
		arg.University,
		arg.Faculty,
		arg.Grade,
		arg.Country,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.University,
		&i.Faculty,
		&i.Grade,
		&i.Country,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultQuestionCount,
		&i.LastSyncAt,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionExpiresAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, username, display_name, avatar_url, bio, university, faculty, grade, country, plan, created_at, updated_at, default_question_count, last_sync_at, stripe_customer_id, stripe_subscription_id, subscription_expires_at
FROM users
WHERE firebase_uid = $1
LIMIT 1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.University,
		&i.Faculty,
		&i.Grade,
		&i.Country,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultQuestionCount,
		&i.LastSyncAt,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, firebase_uid, username, display_name, avatar_url, bio, university, faculty, grade, country, plan, created_at, updated_at, default_question_count, last_sync_at, stripe_customer_id, stripe_subscription_id, subscription_expires_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.University,
		&i.Faculty,
		&i.Grade,
		&i.Country,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultQuestionCount,
		&i.LastSyncAt,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionExpiresAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, firebase_uid, username, display_name, avatar_url, bio, university, faculty, grade, country, plan, created_at, updated_at, default_question_count, last_sync_at, stripe_customer_id, stripe_subscription_id, subscription_expires_at
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.University,
		&i.Faculty,
		&i.Grade,
		&i.Country,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultQuestionCount,
		&i.LastSyncAt,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionExpiresAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    username = CASE WHEN $1::boolean THEN $2::text ELSE username END,
    display_name = CASE WHEN $3::boolean THEN $4::text ELSE display_name END,
    avatar_url = CASE WHEN $5::boolean THEN $6 ELSE avatar_url END,
    bio = CASE WHEN $7::boolean THEN $8 ELSE bio END,
    university = CASE WHEN $9::boolean THEN $10 ELSE university END,
    faculty = CASE WHEN $11::boolean THEN $12 ELSE faculty END,
    grade = CASE WHEN $13::boolean THEN $14 ELSE grade END,
    country = CASE WHEN $15::boolean THEN $16 ELSE country END,
    updated_at = NOW()
WHERE id = $17
RETURNING id, firebase_uid, username, display_name, avatar_url, bio, university, faculty, grade, country, plan, created_at, updated_at, default_question_count, last_sync_at, stripe_customer_id, stripe_subscription_id, subscription_expires_at
`

type UpdateUserParams struct {
	SetUsername    bool           `json:"set_username"`
	Username       string         `json:"username"`
	SetDisplayName bool           `json:"set_display_name"`
	DisplayName    string         `json:"display_name"`
	SetAvatarUrl   bool           `json:"set_avatar_url"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	SetBio         bool           `json:"set_bio"`
	Bio            sql.NullString `json:"bio"`
	SetUniversity  bool           `json:"set_university"`
	University     sql.NullString `json:"university"`
	SetFaculty     bool           `json:"set_faculty"`
	Faculty        sql.NullString `json:"faculty"`
	SetGrade       bool           `json:"set_grade"`
	Grade          sql.NullInt16  `json:"grade"`
	SetCountry     bool           `json:"set_country"`
	Country        sql.NullString `json:"country"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.SetUsername,
		arg.Username,
		arg.SetDisplayName,
		arg.DisplayName,
		arg.SetAvatarUrl,
		arg.AvatarUrl,
		arg.SetBio,
		arg.Bio,
		arg.SetUniversity,
		arg.University,
		arg.SetFaculty,
		arg.Faculty,
		arg.SetGrade,
		arg.Grade,
		arg.SetCountry,
		arg.Country,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.University,
		&i.Faculty,
		&i.Grade,
		&i.Country,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultQuestionCount,
		&i.LastSyncAt,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionExpiresAt,
	)
	return i, err
}

const updateUserQuestionSettings = `-- name: UpdateUserQuestionSettings :one
UPDATE users SET
    default_question_count = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, firebase_uid, username, display_name, avatar_url, bio, university, faculty, grade, country, plan, created_at, updated_at, default_question_count, last_sync_at, stripe_customer_id, stripe_subscription_id, subscription_expires_at
`

type UpdateUserQuestionSettingsParams struct {
	ID                   uuid.UUID `json:"id"`
	DefaultQuestionCount int16     `json:"default_question_count"`
}

func (q *Queries) UpdateUserQuestionSettings(ctx context.Context, arg UpdateUserQuestionSettingsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserQuestionSettings, arg.ID, arg.DefaultQuestionCount)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.University,
		&i.Faculty,
		&i.Grade,
		&i.Country,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultQuestionCount,
		&i.LastSyncAt,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionExpiresAt,
	)
	return i, err
}
