import { Platform, StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#070b10',
  },
  keyboard: {
    flex: 1,
  },
  page: {
    flex: 1,
    backgroundColor: '#070b10',
  },
  quizModalSafeArea: {
    flex: 1,
    backgroundColor: '#070b10',
  },
  quizModalPage: {
    flex: 1,
    backgroundColor: '#070b10',
  },
  quizModalHeader: {
    alignItems: 'flex-start',
    borderBottomColor: '#23313d',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
  },
  quizModalSubtitle: {
    color: '#8a98a8',
    fontSize: 14,
    lineHeight: 20,
  },
  quizAnimatedContent: {
    flex: 1,
  },
  quizFullScreenBody: {
    flex: 1,
  },
  quizQuestionScroll: {
    flex: 1,
  },
  quizQuestionContent: {
    gap: 16,
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 24,
  },
  quizQuestionText: {
    color: '#e6edf3',
    fontSize: 26,
    fontWeight: '700',
    lineHeight: 38,
  },
  quizFooter: {
    alignItems: 'flex-end',
    borderTopColor: '#23313d',
    borderTopWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
  },
  quizArrowButton: {
    alignItems: 'center',
    backgroundColor: '#d7f8e8',
    borderRadius: 999,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  quizArrowButtonText: {
    color: '#070b10',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 26,
  },
  quizSummaryContent: {
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
  },
  header: {
    backgroundColor: '#070b10',
    borderBottomColor: '#23313d',
    borderBottomWidth: 1,
    gap: 4,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
  },
  eyebrow: {
    color: '#8a98a8',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  title: {
    color: '#d7f8e8',
    fontSize: 28,
    fontWeight: '700',
  },
  subtitle: {
    color: '#8a98a8',
    fontSize: 14,
    lineHeight: 20,
  },
  scrollContent: {
    gap: 0,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 20,
  },
  card: {
    backgroundColor: '#101820',
    borderColor: '#23313d',
    borderRadius: 0,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  timelineComposer: {
    borderBottomColor: '#23313d',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  quickActionButton: {
    alignItems: 'center',
    backgroundColor: '#101820',
    borderColor: '#23313d',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 58,
  },
  quickActionButtonPressed: {
    backgroundColor: '#131f29',
    borderColor: '#335062',
  },
  quickActionIcon: {
    backgroundColor: 'rgba(53, 211, 153, 0.15)',
    borderRadius: 999,
    color: '#9ee7c5',
    fontSize: 15,
    fontWeight: '900',
    height: 30,
    lineHeight: 30,
    overflow: 'hidden',
    textAlign: 'center',
    width: 30,
  },
  quickActionText: {
    color: '#e6edf3',
    fontSize: 15,
    fontWeight: '800',
  },
  reviewReminderCard: {
    alignItems: 'center',
    backgroundColor: '#101820',
    borderBottomColor: '#23313d',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 76,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  reviewReminderIcon: {
    backgroundColor: '#d7f8e8',
    borderRadius: 999,
    color: '#070b10',
    fontSize: 18,
    fontWeight: '900',
    height: 42,
    lineHeight: 42,
    overflow: 'hidden',
    textAlign: 'center',
    width: 42,
  },
  timelineOpenArea: {
    gap: 12,
  },
  questionCardPressable: {
    gap: 4,
  },
  innerCard: {
    backgroundColor: '#111820',
    borderColor: '#23313d',
    borderRadius: 12,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  cardTitle: {
    color: '#d7f8e8',
    fontSize: 18,
    fontWeight: '700',
  },
  muted: {
    color: '#8a98a8',
    fontSize: 14,
    lineHeight: 20,
  },
  helper: {
    color: '#8a98a8',
    fontSize: 13,
    lineHeight: 18,
  },
  bodyText: {
    color: '#e6edf3',
    fontSize: 14,
    lineHeight: 22,
  },
  bodyStrong: {
    color: '#e6edf3',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
  },
  stack: {
    gap: 10,
  },
  stackTight: {
    gap: 4,
  },
  flexColumn: {
    flex: 1,
    gap: 2,
  },
  sectionHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  segmented: {
    backgroundColor: '#111820',
    borderColor: '#23313d',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    padding: 4,
  },
  segmentButton: {
    alignItems: 'center',
    borderRadius: 999,
    flex: 1,
    justifyContent: 'center',
    minHeight: 40,
  },
  segmentButtonActive: {
    backgroundColor: '#d7f8e8',
  },
  segmentButtonText: {
    color: '#8a98a8',
    fontSize: 14,
    fontWeight: '600',
  },
  segmentButtonTextActive: {
    color: '#070b10',
  },
  fieldGroup: {
    gap: 6,
  },
  fieldLabel: {
    color: '#e6edf3',
    fontSize: 13,
    fontWeight: '600',
  },
  input: {
    backgroundColor: '#070b10',
    borderColor: '#335062',
    borderRadius: 12,
    borderWidth: 1,
    color: '#e6edf3',
    fontSize: 15,
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  multilineInput: {
    minHeight: 120,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#d7f8e8',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
  },
  primaryButtonPressed: {
    backgroundColor: '#9ee7c5',
  },
  primaryButtonDisabled: {
    backgroundColor: '#334351',
  },
  primaryButtonText: {
    color: '#070b10',
    fontSize: 15,
    fontWeight: '700',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#070b10',
    borderColor: '#23313d',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 16,
  },
  secondaryButtonPressed: {
    backgroundColor: '#111820',
  },
  secondaryButtonDisabled: {
    opacity: 0.5,
  },
  secondaryButtonText: {
    color: '#e6edf3',
    fontSize: 14,
    fontWeight: '600',
  },
  secondaryButtonTextDisabled: {
    color: '#8a98a8',
  },
  smallButton: {
    alignItems: 'center',
    backgroundColor: '#070b10',
    borderColor: '#23313d',
    borderRadius: 999,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  smallButtonText: {
    color: '#e6edf3',
    fontSize: 18,
    fontWeight: '700',
  },
  iconButton: {
    borderColor: '#23313d',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
  },
  iconButtonText: {
    color: '#e6edf3',
    fontSize: 13,
    fontWeight: '600',
  },
  buttonRow: {
    gap: 10,
  },
  inlineButtonRow: {
    flexDirection: 'row',
    gap: 10,
  },
  inlineButtonCell: {
    flex: 1,
  },
  badge: {
    alignItems: 'center',
    backgroundColor: '#111820',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 28,
    paddingHorizontal: 10,
  },
  badgeText: {
    color: '#8a98a8',
    fontSize: 12,
    fontWeight: '700',
  },
  timelineHeader: {
    flexDirection: 'row',
    gap: 12,
  },
  timelineHeaderText: {
    flex: 1,
    gap: 2,
  },
  timelineMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  timelineActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  timelineName: {
    color: '#e6edf3',
    fontSize: 15,
    fontWeight: '700',
  },
  timelineHandle: {
    color: '#8a98a8',
    fontSize: 13,
  },
  timelineDate: {
    color: '#8a98a8',
    fontSize: 12,
  },
  timelineFooter: {
    color: '#8a98a8',
    fontSize: 13,
    fontWeight: '600',
  },
  timelineActionButton: {
    alignItems: 'center',
    backgroundColor: '#070b10',
    borderColor: '#23313d',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
  },
  timelineActionButtonActive: {
    backgroundColor: 'rgba(53, 211, 153, 0.15)',
    borderColor: '#9ee7c5',
  },
  timelineActionText: {
    color: '#e6edf3',
    fontSize: 13,
    fontWeight: '600',
  },
  timelineActionTextActive: {
    color: '#9ee7c5',
  },
  modalBackdrop: {
    backgroundColor: 'rgba(15, 20, 25, 0.45)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalDismissArea: {
    flex: 1,
  },
  modalSheet: {
    backgroundColor: '#070b10',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '88%',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
  },
  modalHandle: {
    alignSelf: 'center',
    backgroundColor: '#335062',
    borderRadius: 999,
    height: 5,
    marginBottom: 12,
    width: 48,
  },
  commentSection: {
    borderTopColor: '#23313d',
    borderTopWidth: 1,
    gap: 10,
    paddingTop: 12,
  },
  commentComposerActions: {
    alignItems: 'flex-end',
  },
  commentCard: {
    backgroundColor: '#111820',
    borderColor: '#23313d',
    borderRadius: 12,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  avatarChip: {
    alignItems: 'center',
    backgroundColor: '#d7f8e8',
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  avatarChipText: {
    color: '#070b10',
    fontSize: 15,
    fontWeight: '700',
  },
  profileHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  profileTextColumn: {
    flex: 1,
    gap: 2,
  },
  profileName: {
    color: '#e6edf3',
    fontSize: 20,
    fontWeight: '700',
  },
  profileHandle: {
    color: '#8a98a8',
    fontSize: 14,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  profileStat: {
    backgroundColor: '#111820',
    borderColor: '#23313d',
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    padding: 12,
  },
  profileStatValue: {
    color: '#e6edf3',
    fontSize: 16,
    fontWeight: '700',
  },
  profileStatLabel: {
    color: '#8a98a8',
    fontSize: 12,
  },
  stepperRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
  },
  stepperValue: {
    alignItems: 'center',
    backgroundColor: '#111820',
    borderColor: '#23313d',
    borderRadius: 999,
    borderWidth: 1,
    flex: 1,
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  stepperValueText: {
    color: '#e6edf3',
    fontSize: 15,
    fontWeight: '700',
  },
  optionText: {
    color: '#e6edf3',
    fontSize: 14,
    lineHeight: 20,
  },
  choiceButton: {
    backgroundColor: '#070b10',
    borderColor: '#23313d',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  choiceButtonActive: {
    backgroundColor: '#d7f8e8',
    borderColor: '#d7f8e8',
  },
  choiceButtonText: {
    color: '#e6edf3',
    fontSize: 14,
    lineHeight: 20,
  },
  choiceButtonTextActive: {
    color: '#070b10',
  },
  resultPreview: {
    backgroundColor: '#111820',
    borderColor: '#23313d',
    borderRadius: 12,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  resultTitle: {
    color: '#e6edf3',
    fontSize: 16,
    fontWeight: '700',
  },
  resultMeta: {
    color: '#8a98a8',
    fontSize: 13,
  },
  resultUrl: {
    color: '#9ee7c5',
    fontSize: 13,
    lineHeight: 18,
  },
  resultBody: {
    color: '#e6edf3',
    fontSize: 15,
    lineHeight: 22,
  },
  tabBar: {
    backgroundColor: '#070b10',
    borderTopColor: '#23313d',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  tabButton: {
    alignItems: 'center',
    borderRadius: 999,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
  },
  tabButtonActive: {
    backgroundColor: '#111820',
  },
  tabButtonPressed: {
    opacity: 0.8,
  },
  tabButtonText: {
    color: '#8a98a8',
    fontSize: 22,
    fontWeight: '800',
  },
  tabButtonTextActive: {
    color: '#d7f8e8',
    fontWeight: '700',
  },
  errorText: {
    color: '#ff6673',
    fontSize: 14,
    lineHeight: 20,
  },
  successText: {
    color: '#35d399',
    fontSize: 14,
    lineHeight: 20,
  },
  debugText: {
    color: '#8a98a8',
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
    fontSize: 12,
    lineHeight: 18,
  },
})
